"""first commit

Revision ID: bbf6bf359982
Revises: 
Create Date: 2021-10-16 21:15:58.340408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6bf359982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoja_automotor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=240), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('propietario', sa.String(length=30), nullable=True),
    sa.Column('identificacion_interna', sa.String(length=30), nullable=True),
    sa.Column('tarjeta_propiedad', sa.String(length=40), nullable=True),
    sa.Column('fecha_expedicion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('avaluo', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(length=40), nullable=True),
    sa.Column('clase_vehiculo', sa.String(length=40), nullable=True),
    sa.Column('marca', sa.String(length=30), nullable=True),
    sa.Column('combustible', sa.String(length=30), nullable=True),
    sa.Column('modelo', sa.String(length=30), nullable=True),
    sa.Column('placa', sa.String(length=30), nullable=True),
    sa.Column('cilindraje', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('numero_motor', sa.String(length=40), nullable=True),
    sa.Column('numero_serie', sa.String(length=40), nullable=True),
    sa.Column('numero_chasis', sa.String(length=40), nullable=True),
    sa.Column('tipo_caja', sa.String(length=40), nullable=True),
    sa.Column('capacidad', sa.String(length=40), nullable=True),
    sa.Column('path_tarjeta_propiedad', sa.String(length=30), nullable=True),
    sa.Column('filename_tarjeta_propiedad', sa.String(length=30), nullable=True),
    sa.Column('path_soat', sa.String(length=30), nullable=True),
    sa.Column('filename_soat', sa.String(length=30), nullable=True),
    sa.Column('path_tecno', sa.String(length=30), nullable=True),
    sa.Column('filename_tecno', sa.String(length=30), nullable=True),
    sa.Column('path_foto1', sa.String(length=30), nullable=True),
    sa.Column('filename_foto1', sa.String(length=30), nullable=True),
    sa.Column('path_foto2', sa.String(length=30), nullable=True),
    sa.Column('filename_foto2', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoja_automotor_fecha_creacion'), 'hoja_automotor', ['fecha_creacion'], unique=False)
    op.create_table('hojaobra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=240), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('localizacion', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=40), nullable=True),
    sa.Column('radicado_solicitud', sa.String(length=30), nullable=True),
    sa.Column('ingeniero_a_cargo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_socializacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_terminacion', sa.DateTime(), nullable=True),
    sa.Column('path_cuadro_base_datos', sa.String(length=30), nullable=True),
    sa.Column('path_programa_visitas', sa.String(length=30), nullable=True),
    sa.Column('path_visita_tecnica', sa.String(length=30), nullable=True),
    sa.Column('path_acta_comite_tecnico', sa.String(length=30), nullable=True),
    sa.Column('path_certificado_banco_proyectos', sa.String(length=30), nullable=True),
    sa.Column('path_presupuesto', sa.String(length=30), nullable=True),
    sa.Column('path_estudios_previos', sa.String(length=30), nullable=True),
    sa.Column('path_estado_redes', sa.String(length=30), nullable=True),
    sa.Column('path_planos', sa.String(length=30), nullable=True),
    sa.Column('path_ensayo_laboratorio', sa.String(length=30), nullable=True),
    sa.Column('path_plan_manejo_ambiental', sa.String(length=30), nullable=True),
    sa.Column('path_registro_fotografico', sa.String(length=30), nullable=True),
    sa.Column('path_informe_diario', sa.String(length=30), nullable=True),
    sa.Column('path_acta_de_entrega', sa.String(length=30), nullable=True),
    sa.Column('path_consolidacion_documentos', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_vial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nombre', sa.String(length=240), nullable=True),
    sa.Column('descripcion', sa.String(length=240), nullable=True),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('ancho_promedio', sa.Integer(), nullable=True),
    sa.Column('longitud', sa.Integer(), nullable=True),
    sa.Column('visitador', sa.String(length=30), nullable=True),
    sa.Column('coordenadas_inicio', sa.Integer(), nullable=True),
    sa.Column('coordenadas_final', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('tipo_de_calzada', sa.String(length=30), nullable=True),
    sa.Column('conexion_inicio', sa.String(length=30), nullable=True),
    sa.Column('conexion_final', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_inventario_vial_fecha'), 'inventario_vial', ['fecha'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('PQR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_recibido', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=240), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('peticionario', sa.String(length=30), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('path_respuesta', sa.String(length=30), nullable=True),
    sa.Column('filename_respuesta', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_PQR_fecha_recibido'), 'PQR', ['fecha_recibido'], unique=False)
    op.create_index(op.f('ix_PQR_fecha_respuesta'), 'PQR', ['fecha_respuesta'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_index(op.f('ix_PQR_fecha_respuesta'), table_name='PQR')
    op.drop_index(op.f('ix_PQR_fecha_recibido'), table_name='PQR')
    op.drop_table('PQR')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_inventario_vial_fecha'), table_name='inventario_vial')
    op.drop_table('inventario_vial')
    op.drop_table('hojaobra')
    op.drop_index(op.f('ix_hoja_automotor_fecha_creacion'), table_name='hoja_automotor')
    op.drop_table('hoja_automotor')
    # ### end Alembic commands ###
